### ISSUE TITLE
Small Issue with Avatar Dynamics

### ISSUE THREAD

**Issue by MrDj200** [BlackStartx/VRC-Gesture-Manager#3] opened 2022-04-25 04:37 UTC
Hi,

Using the new AvatarDynamics, you're able to grab PhysBones in the Game window in Play mode. You're also able to get Paramters depicting whether or not a physbone is being grabbed etc.
The parameter shows up in GestureManagers Debug menu, however sometimes when grabbing a PhysBone, it doesn't update the parameter. The same issue occurs with contacts. 
Most of the time, the only way to get GestureManager to recognize them again, is to restart Unity.

I'm using the newest (at the point of writing this) VRCSDK
Unity 2019.4.31f1
and GestureManager 3.4

Edit:

When leaving PlayMode, there is the following Warning in the Console:
`Assets/GestureManager/Scripts/Editor/Modules/Vrc3/ModuleVrc3.cs(109): PlayableGraph was not destroyed`
![image](https://user-images.githubusercontent.com/5685500/165022228-3a367abe-7c3d-4511-9546-757a55287876.png)

**Comment by MrDj200** [comment] 2022-04-26 18:46
Good to hear!
I forgot to mention, when you want to test the contacts in unity, it only drives parameters that are on the avatar controller, not the ones on FXController etc.
Would be very appreciated if you could make the sdk drive the parameters in the vrc related controllers as well!

Thanks for your hard work on this project :)

**Comment by BlackStartx** [comment] 2022-04-26 19:12
Hi again~

The future release is **_currently_** working with all the parameters driven by the contacts of your avatar with no need of any controller in the Animator at all~ ^-^

So yooshhh, I can confirm that it will work like that! :D

Thanks again for everything and you for your words~ ❤️

**Comment by BlackStartx** [comment] 2022-04-29 00:30
Hi dj~ :3 

I've released the new 3.5 version of my tool with the AvatarDynamics support~ ^-^
Now all the parameters should be updating correctly while using the Gesture Manager~

There is also A LOT of new stuff too, if you wish you can check the changelog in the release tab! :D

I'll leave this Issue open in case you need anything or in case you want to say something~
Otherwise feel free to close it~ ^-^

Hope you will like the new update~ :3 ♥

**Comment by MrDj200** [comment] 2022-04-30 04:41
Hey, everything works great!

However, it seems you are not checking if `Allow Self` on ContactReceivers is checked.
I need a receiver and sender at the same place to check if people are touching noses for example. I'm using a custom collision tag with `Allow Self` disabled, and it works in vrc, but in gesture manager, the receiver is being triggered by the sender on myself, which is not intended behavior. 

Not sure if this is too much of an edge case, or something that will end up happening a lot, so I don't know if it would be worth implementing a solution for this.

Anyways, thanks a lot for the update :)

**Comment by BlackStartx** [comment] 2022-04-30 15:09
Ohhh, that's actually a really big issue~ ;w;
Thank you so much for discovering that! ♥

Since my tool is hooking to the built-in contact simulation of the SDK this may also be considered a VRChat SDK issue~

In any case I will soon release a fixed package here with the check for the allowSelf parameter hard-coded in the GestureManager~ ^-^

P.S: By saying "VRChat SDK simulation issue" I don't mean by any case that it's their fault or that their simulation is bad.

The built-in simulation in the SDK is **AMAZING**, they are doing 99% of the job and it's so nice to see this kind of stuff built-in in the Unity SDK~

What I mean is that this may also be fixed internally in the future with a new SDK update from the VRChat team. ^-^

And since other people may experience this issue I'll close and link this to a new issue focused on this problem~

Thanks again for discovering that~ ♥

**Closed by BlackStartx** 2022-04-30 15:09 UTC
