### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by StriKejk** [BlackStartx/VRC-Gesture-Manager#57] opened 2024-06-16 21:22 UTC
Trying to compile a Unity 2022 Avatar Project with the gesture manager package active leads to multiple compiling errors.

Creator Companion: 2.3.1
Unity: 2022.3.22f1
Project: 2022 Avatar
VRChat Package Resolver Tool: 0.1.29
VRChat SDK - Base: 3.6.1
VRChat SDK - Avatars: 3.6.1
Gesture Manager: 3.9.1

Errors:
`Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(25,49): error CS0234: The type or namespace name 'Vrc3' does not exist in the namespace 'BlackStartX.GestureManager.Editor.Modules' (are you missing an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(263,10): error CS0246: The type or namespace name 'RadialMenu' could not be found (are you missing a using directive or an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(262,3): error CS0246: The type or namespace name 'RadialMenu' could not be found (are you missing a using directive or an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(40,67): error CS0234: The type or namespace name 'Vrc3' does not exist in the namespace 'BlackStartX.GestureManager.Editor.Modules' (are you missing an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(41,68): error CS0234: The type or namespace name 'Vrc3' does not exist in the namespace 'BlackStartX.GestureManager.Editor.Modules' (are you missing an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(66,72): error CS0234: The type or namespace name 'Vrc3' does not exist in the namespace 'BlackStartX.GestureManager.Editor.Modules' (are you missing an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(102,71): error CS0234: The type or namespace name 'Vrc3' does not exist in the namespace 'BlackStartX.GestureManager.Editor.Modules' (are you missing an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(117,70): error CS0234: The type or namespace name 'Vrc3' does not exist in the namespace 'BlackStartX.GestureManager.Editor.Modules' (are you missing an assembly reference?)
Packages\lyuma.av3emulator\Editor\GestureManagerBridge\GestureManagerAv3MenuEditor.cs(132,72): error CS0234: The type or namespace name 'Vrc3' does not exist in the namespace 'BlackStartX.GestureManager.Editor.Modules' (are you missing an assembly reference?)`

**Comment by BlackStartx** [comment] 2024-06-17 00:21
Hi StriKejk~ 🌺 

First of all, I can see you also have the `lyuma.av3emulator` package in your project, as stated by the errors messages.
But you didn't mention it in your project dependency:

> Creator Companion: 2.3.1
> Unity: 2022.3.22f1
> Project: 2022 Avatar
> VRChat Package Resolver Tool: 0.1.29
> VRChat SDK - Base: 3.6.1
> VRChat SDK - Avatars: 3.6.1
> Gesture Manager: 3.9.1

My guess is that you have an outdated version of their package? 
Since the latest versions of our tools (Gesture Manager 3.9.1 & Av3Emulator 3.4.4) are indeed compatible if I recall correctly~

**Comment by BlackStartx** [comment] 2024-06-24 13:38
I'll close the issue since there hasen't been any update in a week~

Hope the problem is solved! 👍🏻 
- BlackStartx

**Closed by BlackStartx** 2024-06-24 13:38 UTC

**Comment by notbrianbob** [comment] 2025-04-28 22:11
Been getting this exact same issue on and off even till now. It looks like the cause is from the order in which the packages are installed (Av3Emulator and Gesture Manager). The way I was able to get the errors to stop was to remove Av3Emulator and re add it back. More exactly, I had both installed, I was in the android build selected with the errors showing, re installed Av3Emulator and the errors went away.
